// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSx_LQ1LMujnRnCFDjB8Fsgbpzn-z22Rs',
    appId: '1:807145542991:web:b8563944647cd042c2a13a',
    messagingSenderId: '807145542991',
    projectId: 'hitlook-app',
    authDomain: 'hitlook-app.firebaseapp.com',
    storageBucket: 'hitlook-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVW_NQDz2615HHfv9DvDbAGVLaZxyVCs',
    appId: '1:807145542991:android:845fd33c83baeecdc2a13a',
    messagingSenderId: '807145542991',
    projectId: 'hitlook-app',
    storageBucket: 'hitlook-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZotNzz2au1PusQeccVc1RczjiZSA_WAQ',
    appId: '1:807145542991:ios:8f54c4325326d8cac2a13a',
    messagingSenderId: '807145542991',
    projectId: 'hitlook-app',
    storageBucket: 'hitlook-app.firebasestorage.app',
    iosBundleId: 'com.livelong.livelong',
  );
}
